fail on failed tests run by sonar-scanner; don't run tests in lein; publish test results on PR

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,6 +40,35 @@ jobs:
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
           -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
 
+      - name: Get list of tests
+        if: always()
+        id: tests
+        uses: Rishabh510/Path-lister-action@master
+        with:
+          path: "code/test-reports"
+          type: ".xml"
+
+      - name: Fail on failed tests
+        if: always()
+        run: |
+          sudo apt-get install -y libxml2-utils
+          echo "Found ${{ steps.tests.outputs.path_count }} test report(s)"
+          if [[ ${{ steps.tests.outputs.path_count }} < 1 ]]; then
+             echo "ERROR: No unit test reports collected."
+             exit 1
+          fi
+          for f in ${{ steps.tests.outputs.paths }}; do
+            echo "=== $f ==="
+            if [[ $(xmllint --xpath "string(//testsuite/@failures)" $f) > 1 ]]; then
+               echo TEST FAILED: $f
+               exit 1
+            fi
+            if [[ $(xmllint --xpath "string(//testsuite/@errors)" $f) > 1 ]]; then
+               echo TEST ERRORED: $f
+               exit 1
+            fi
+          done
+
       - name: SonarQube Quality Gate check
         uses: sonarsource/sonarqube-quality-gate-action@v1.0.0
         # Force to fail step after specific time
@@ -66,17 +95,23 @@ jobs:
         run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
         id: extract_branch
 
-      - name: Build and test
+      - name: Build
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        run: lein do clean, test, jar, install
+        run: lein do clean, jar, install
 
       - name: Deploy
         env:
             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
             AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         run: lein deploy
+
+      - name: Publish Unit Test Results
+        uses: EnricoMi/publish-unit-test-result-action@v1
+        if: always()
+        with:
+          files: code/test-reports/TEST-*.xml
 
   job-notify:
     if: always()
